# File: .github/workflows/example.yml

on: [push]

name: myvnet

jobs:

  execute-sample:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az group list
