# File: .github/workflows/example.yml

on: [push]

name: myvnet

jobs:

  execute-sample:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
         # Deploy ARM template
    - name: deploy_vnet
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.LAB_AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.LAB_AZURE_RG }}
        template: ./code/Arrm.json
        parameters: ./code/parameters.json
