# File: .github/workflows/ex1.yml

on: [push]

name: myvm

jobs:

  execute-sample:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
         # Deploy ARM template
    - name: deploy_vm
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.LAB_AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.LAB_AZURE_RG }}
        template: ./code/vm.json
        #parameters: ./code/parameters.json
