on:

  workflow_dispatch:

 

name: sp-dev

jobs:

  deploy:

    environment: Dev

    runs-on: ubuntu-latest

    steps:

      # Checkout code

    - uses: actions/checkout@main



      # Log into Azure

    - uses: azure/login@v1

      with:

        creds: ${{ secrets.AZURE_CONNECTION_ID }}



    - name: deploy_dev_storage

      uses: azure/arm-deploy@v1

      with:

        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_DEV }}

        resourceGroupName: ${{ secrets.AZURE_RG_DEV }}

        template: ./code/storage.json
